JENKINS_CLI_PREFIX: "java -jar /home/centos/jenkins-cli.jar -s http://54.158.215.99:8080/ -auth {{JUSER}}:{{JPASS}} -webSocket"



#export JENKINS_CLI_PREFIX: "java -jar /home/centos/jenkins-cli.jar -s http://54.158.215.99:8080/ -auth {{JUSER}}:{{JPASS}}  -webSocket"
